# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "globo-centos58"
  config.vm.box_url = "../globo-centos58-x86_64-v2.box"
  config.vm.network :private_network, ip: "192.168.222.20"
  config.vm.network :forwarded_port, guest: 9000, host: 9300
  config.vm.network :forwarded_port, guest: 1980, host: 1980
  config.vm.synced_folder "/Users/m.monteiro/Documents/dev/export", "/vagrant", :nfs => true

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "4096"]
  end
end
