# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

VAGRANTFILE_API_VERSION = "2"
PROVISION = "puppet" # chef (future...)

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "repocache"
  config.vm.box_url = "../centos-510-x64-vbox436.box"
  config.vm.synced_folder "/Users/m.monteiro/Documents/dev/export", "/vagrant", :nfs => true
  config.vm.synced_folder "templates", "/tmp/vagrant-puppet/templates"
  config.vm.synced_folder "files", "/tmp/vagrant-puppet/files"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define :web do |web|
    web.vm.box = "#{config.vm.box}"
    web.vm.hostname = "#{config.vm.box}.localhost"
    web.vm.network :private_network, ip: "192.168.222.202"
    web.vm.network :forwarded_port, guest: 3129, host: 3129
    web.vm.network :forwarded_port, guest: 3128, host: 3128
    if (PROVISION == "puppet")
        web.vm.provision :puppet do |puppet|
          puppet.manifests_path = "manifests"
          puppet.module_path    = "modules"
          puppet.options        = ["--templatedir", "/tmp/vagrant-puppet/templates"]
          puppet.manifest_file  = "init.pp"
        end
    end
  end

end
