# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

VAGRANTFILE_API_VERSION = "2"
PROVISION = "puppet" # chef (future...)

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "myvertx"
  config.vm.box_url = "../centos-6.4-x86_64-v20130731.box"
  config.vm.synced_folder "/Users/m.monteiro/Documents/dev/export", "/vagrant", :nfs => true
  config.vm.synced_folder "puppet/templates", "/tmp/vagrant-puppet/templates"
  config.vm.synced_folder "jdk", "/tmp/jdk"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define :web do |web|
    web.vm.box = "web.#{config.vm.box}"
    web.vm.hostname = "web.#{config.vm.box}.localhost"
    web.vm.network :private_network, ip: "192.168.222.40"
    web.vm.network :forwarded_port, guest: 8080, host: 8080
    if (PROVISION == "puppet")
        web.vm.provision :puppet do |puppet|
          puppet.manifests_path = "puppet/manifests/myvertx"
          puppet.module_path    = "puppet/modules"
          puppet.options        = ["--templatedir", "/tmp/vagrant-puppet/templates/myvertx"]
          puppet.manifest_file  = "init.pp"
        end
    end
  end

end
